version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: bigganbondhu-backend:${TAG:-latest}
    container_name: bigganbondhu-backend
    restart: always
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    volumes:
      - ./backend/data:/app/data
    environment:
      - TZ=${TZ:-UTC}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - MAX_WORKERS=${MAX_WORKERS:-4}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Frontend service (commented by default)
  frontend:
    build:
      context: ./frontend/bigganbondhu
      dockerfile: Dockerfile
    image: bigganbondhu-frontend:${TAG:-latest}
    container_name: bigganbondhu-frontend
    restart: always
    ports:
      - "${FRONTEND_PORT:-3000}:80"
    environment:
      - VITE_API_URL=${API_URL:-http://localhost:8000}
    depends_on:
      - backend
  #     - VITE_API_URL=http://localhost:8000
