version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: bigganbondhu-backend:latest
    container_name: bigganbondhu-backend
    restart: always
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    volumes:
      - ./data:/app/data
    environment:
      - TZ=${TZ:-UTC}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - MAX_WORKERS=${MAX_WORKERS:-4}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
