name: Deploy Frontend

on:
  push:
    branches: [main]
    paths:
      - "frontend/**"
      - ".github/workflows/deploy-frontend.yml"
  workflow_dispatch: # Allow manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend/bigganbondhu
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/bigganbondhu-frontend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # This commented section is if you want to deploy the frontend to the same VM
      # - name: Setup SSH
      #   uses: webfactory/ssh-agent@v0.9.0
      #   with:
      #     ssh-private-key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
      #
      # - name: Adding Known Hosts
      #   run: |
      #     mkdir -p ~/.ssh
      #     ssh-keyscan -H ${{ secrets.GCP_VM_IP }} >> ~/.ssh/known_hosts
      #
      # - name: Deploy to GCP VM
      #   env:
      #     GCP_VM_IP: ${{ secrets.GCP_VM_IP }}
      #     GCP_VM_USER: ${{ secrets.GCP_VM_USER }}
      #   run: |
      #     # Update docker-compose on VM to include frontend
      #     ssh ${{ secrets.GCP_VM_USER }}@${{ secrets.GCP_VM_IP }} "docker pull ghcr.io/${{ github.repository_owner }}/bigganbondhu-frontend:latest && cd ~/bigganbondhu && docker-compose up -d"
